#! /bin/sh

. "${HOME}/.zprofile"
xsetroot -cursor_name left_ptr
hsetroot -extend "${HOME}/dotfiles/wallpaper/gnu.png"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
