#! /bin/sh

ESPIDFPATH="$XDG_DATA_HOME/esp-idf"

[ -d "$ESPIDFPATH" ] || { echo "No esp-idf directory. Check $ESPIDFPATH"; exit 1; }
[ -n "$IDF_TOOLS_PATH" ] || { echo "Check IDF_TOOLS_PATH env var"; exit 1; }
[ -d "$IDF_TOOLS_PATH" ] || { echo "Esp-idf tools not installed. Check $IDF_TOOLS_PATH"; exit 1; }

. "$ESPIDFPATH/export.sh"
export RPROMPT="(esp-idf)"
